
const data = [
    {
        id:1,
        image:'https://www.ecotienda.pe/wp-content/uploads/2022/08/7753028000721.jpg',
        name:'Agua de Jamaica',
        price: 20.99,
        category: 'Bebidas',
        company: 'Beberash',
        description: 'Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge',
    },
    {
        id:2,
        image:'https://www.ecotienda.pe/wp-content/uploads/2022/08/7753028000653-400x400.jpg',
        name:'Bebida de piña y camu camu',
        price:44.99,
        category: 'Bebidas',
        company: 'Beberash',
        description: 'Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge',
    },
    {
        id:3,
        image:'https://www.ecotienda.pe/wp-content/uploads/2022/07/Aceite-de-coco-Bioselva-1000ml-400x400.jpg',
        name:'Aceite de coco',
        price:29.99,
        category: 'Aceites',
        company: 'Bio Selva',
        description: 'Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge',
    },
    {
        id:4,
        image:'https://www.ecotienda.pe/wp-content/uploads/2022/08/857190000279.jpg',
        name:'Aceite de Almendra',
        price:19.99,
        category: 'Aceites',
        company: 'La Tourangelle',
        description: 'Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge',
    },
    {
        id:5,
        image:'https://www.ecotienda.pe/wp-content/uploads/2022/07/Mango-deshidratado-Snap-250g-400x400.jpg',
        name:'Mango deshidratado',
        price:39.99,
        category: 'Frutos secos',
        company: 'Snap',
        description: 'Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge',
    },
    {
        id:6,
        image:'https://www.ecotienda.pe/wp-content/uploads/2022/07/Aguaymanto-deshidratado-Snap-250g-400x400.jpg',
        name:'Aguaymanto deshidratado',
        price:49.99,
        category: 'Frutos secos',
        company: 'Snap',
        description: 'Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge',
    },
    {
        id:7,
        image:'https://www.ecotienda.pe/wp-content/uploads/2022/07/Granola-mix-de-avena-y-canela-La-Purita-400gr-400x400.jpg',
        name:'Granola mix de avena y canela',
        price:24.99,
        category: 'Cereales',
        company: 'La Purita',
        description: 'Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge',
    },
    {
        id:8,
        image:'https://www.ecotienda.pe/wp-content/uploads/2022/08/736684998035.jpg',
        name:'Mantequilla de maní',
        price:59.99,
        category: 'Mantequillas',
        company: 'La Purita',
        description: 'Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge',
    },
    {
        id:9,
        image:'https://www.ecotienda.pe/wp-content/uploads/2022/08/689407947981-400x400.jpg',
        name:'Granola cholocale y avellandas',
        price:49.99,
        category: 'Cereales',
        company: 'Almonte',
        description: 'Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge',
    },
    {
        id:10,
        image:'https://www.ecotienda.pe/wp-content/uploads/2022/08/689407951322-400x400.jpg',
        name:'Cacao en polvo',
        price:24.99,
        category: 'Chocolate',
        company: 'Almonte',
        description: 'Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge',
    },
    {
        id:11,
        image:'https://www.ecotienda.pe/wp-content/uploads/2022/08/689407951315-400x400.jpg',
        name:'Granola diabet',
        price:32.99,
        category: 'Cereales',
        company: 'Almonte',
        description: 'Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge',
    },
    {
        id:12,
        image:'https://www.ecotienda.pe/wp-content/uploads/2022/07/Aceite-de-Canola-en-spray-La-Tourangelle-147ml-400x400.jpg',
        name:'Aceite de canola en spray',
        price:49.99,
        category: 'Aceites',
        company: 'La Tourangelle',
        description: 'Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge',
    },
];

export default data;